const songs = [
  "Under the skin",
  "Scent of you",
  "BUZZ LOVE",
  "The Final Countdown",
  "W.O.L.F.",
  "Blind Love",
  "FIREWORK",
  "Road Not Taken",
  "The moon is beautiful",
  "War Cry",
  "Dropkick",
  "Really Crazy",
  "ALIEN",
  "Melody",
  "Running with the pack",
  "Maybe",
  "Samidare",
  "Scar to Scar",
  "Koegawari",
  "Aoarashi",
  "Imprinted",
  "Beat the odds",
  "MEME",
  "Feel the pulse",
  "Jyuugoya",
  "Big suki",
  "Yukiakari",
  "Deer Hunter",
  "Illumination",
  "Crescent moon's wish",
  "Magic Hour",
  "Wonderful World",
  "Extraordinary day",
  "Go in Blind",
  "Run Wild",
  "Wolf Type",
  "Back to Life",
  "Lunatic",
  "MISMATCH",
  "Rush",
  "Heartbreak Time Machine",
  "Who am I",
  "We on Fire",
  "Bewitched",
  "HOTLINE",
  "Sakura-iro Yell",
  "For us",
  "Mark on Me",
  "Good Boy",
  "Love Jang",
  "Accelerate",
  "Empty",
  "Night to howl!",
];